version = "1.3.0"
builder = "spa"

[template_settings]
text-color = "#FFFFFF"
accent-color = "#D82F86"
background-color = "#301F6E"
highlight-color = "#04947A"
autoreload = "1"
custom-color = "#2DE2E6"
youtube-embed-params = "autoplay=1"
